# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CMS Gabriel Alexander
email: office@gabriel-alexander.at
description: > # this means to ignore newlines until "baseurl:"
  On this pretty basic jekyll page, you will find my final submissions for
  cms course at FH-Salzburg.
baseurl: "/staticSiteGenerator" # the subpath of your site, e.g. /blog
url: "http://gabsi20.github.io" # the base hostname & protocol for your site
twitter_username: SbgGabriel
github_username:  gabsi20



# Build settings
markdown: kramdown
